In [5]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import numpy

# Fetching the relevant data

## Data wrangling

The process of transforming and mapping data from one "raw" data form into another format with the intent of making it more appropriate and valuable for a variety of downstream purposes such as analytics.

In this case, the goal is to end up with five columns which include: District, Local Revenue, State Revenue, Federal Revenue and Total.

In [8]:
# inpsect what the data looks like
df=pd.read_csv('ELSI_California_district_revenue_2016_2017.csv')
df.head(10)

,Agency Name,State Name [District] Latest available year,Local_Property Taxes,Local_General Sales Taxes,Local_Public Utility Taxes,Local_Individual_and_Corp_Income Taex,Local_All Other Taxes,Local_Parent Government Contributions,Local_Revenue_Cities and Counties,Local_Other School Systems,...,Federal_Child Nutrition Act,Federal_ Eisenhower Math and Science,Federal_Drug_Free_Schools,Federal_Vocational Education,Federal_ All Other Fed_Aid Through State,Federal_Nonspecified,Federal_Impact Aid,Federal_Bilingual Education,Federal_Native American,Federal_All Other Federal Aid
0,ABC UNIFIED,California,32494000,0,0,0,0,†,7880000,2725000,...,6058000,1140000,483000,210000,2284000,0,0,316000,0,0
1,ACALANES UNION HIGH,California,53504000,0,0,0,10444000,†,1198000,2146000,...,130000,75000,0,47000,68000,0,0,7000,0,0
2,ACKERMAN CHARTER,California,1276000,0,0,0,0,†,40000,156000,...,98000,14000,0,0,0,0,0,0,0,0
3,ACTON-AGUA DULCE UNIFIED,California,5233000,0,0,0,0,†,127000,2561000,...,287000,49000,0,13000,29000,0,0,10000,0,0
4,ADELANTO ELEMENTARY,California,7943000,0,0,0,0,†,1094000,151000,...,4571000,177000,0,0,93000,0,0,213000,0,0
5,ALAMEDA CNTY. STUDENT EXCHANGE PROG.,California,–,–,–,–,–,†,–,–,...,–,–,–,–,–,–,–,–,–,–
6,ALAMEDA COUNTY OFFICE OF EDUCATION,California,†,†,†,†,†,25531000,1436000,3671000,...,0,750000,0,0,2722000,0,0,0,55000,0
7,ALAMEDA UNIFIED,California,40352000,0,0,0,12145000,†,1850000,5065000,...,1847000,243000,0,47000,661000,0,0,203000,0,24000
8,ALBANY CITY UNIFIED,California,14526000,0,0,0,6211000,†,35000,383000,...,354000,46000,0,0,100000,0,0,67000,0,0
9,ALEXANDER VALLEY UNION ELEMENTARY,California,1398000,0,0,0,0,†,0,102000,...,15000,1000,0,0,19000,0,0,3000,0,0

In [9]:
# See all the columns in the dataframe

df.columns

Index(['Agency Name', 'State Name [District] Latest available year',
       'Local_Property Taxes', 'Local_General Sales Taxes',
       'Local_Public Utility Taxes', 'Local_Individual_and_Corp_Income Taex',
       'Local_All Other Taxes', 'Local_Parent Government Contributions',
       'Local_Revenue_Cities and Counties', 'Local_Other School Systems',
       'Local_Tuition Fees_Pupils and Parents',
       'Local_Transp_ Fees_Pupils and Parents', 'Local_School Lunch Revenues',
       'Local_Textbook Sales and Rentals', 'Local_Student Activity Receipts',
       'Local_Other Sales and Service Rev', 'Local_Student Fees NonSpecified',
       'Local_Interest Earnings', 'Local_Miscellaneous Other Local Rev',
       'Local_Special Processing', 'Local_Rents and Royalties',
       'Local_Sale of Property', 'Local_Fines and Forfeits',
       'Local_Private Contributions', 'State_General Formula Assistance',
       'State_Special Education Programs', 'State_Transportation Programs',
       'State_Staff Improvement Programs',
       'State_Compensat and Basic Skills Prog',
       'State_Vocational Education Programs',
       'State_Capital Outlay and Debt ServProg',
       'State_Bilingual Education Programs',
       'State_Gifted and Talented Programs', 'State_School Lunch Programs',
       'State_All Other Rev', 'State_Payment for LEA Empl_Benefits',
       'State_Other State Payments', 'State_Non-Specified',
       'Federal_Federal Title I Revenue', 'Federal_Children with Disabilities',
       'Federal_Child Nutrition Act', 'Federal_ Eisenhower Math and Science',
       'Federal_Drug_Free_Schools', 'Federal_Vocational Education',
       'Federal_ All Other Fed_Aid Through State', 'Federal_Nonspecified',
       'Federal_Impact Aid', 'Federal_Bilingual Education',
       'Federal_Native American', 'Federal_All Other Federal Aid'],
      dtype='object')

In [10]:
# values types seem to be all strings

df.values

array([['ABC UNIFIED', 'California', '32494000', ..., '316000', '0', '0'],
       ['ACALANES UNION HIGH', 'California', '53504000', ..., '7000', '0',
        '0'],
       ['ACKERMAN CHARTER', 'California', '1276000', ..., '0', '0', '0'],
       ...,
       ['† indicates that the data are not applicable.', nan, nan, ...,
        nan, nan, nan],
       ['– indicates that the data are missing.', nan, nan, ..., nan, nan,
        nan],
       ['‡ indicates that the data do not meet NCES data quality standards.',
        nan, nan, ..., nan, nan, nan]], dtype=object)

In [11]:
# selecting the columns to change values from string to numeric
all_revenue = df.iloc[:, 2:]
all_revenue

,Local_Property Taxes,Local_General Sales Taxes,Local_Public Utility Taxes,Local_Individual_and_Corp_Income Taex,Local_All Other Taxes,Local_Parent Government Contributions,Local_Revenue_Cities and Counties,Local_Other School Systems,Local_Tuition Fees_Pupils and Parents,Local_Transp_ Fees_Pupils and Parents,...,Federal_Child Nutrition Act,Federal_ Eisenhower Math and Science,Federal_Drug_Free_Schools,Federal_Vocational Education,Federal_ All Other Fed_Aid Through State,Federal_Nonspecified,Federal_Impact Aid,Federal_Bilingual Education,Federal_Native American,Federal_All Other Federal Aid
0,32494000,0,0,0,0,†,7880000,2725000,1153000,0,...,6058000,1140000,483000,210000,2284000,0,0,316000,0,0
1,53504000,0,0,0,10444000,†,1198000,2146000,557000,0,...,130000,75000,0,47000,68000,0,0,7000,0,0
2,1276000,0,0,0,0,†,40000,156000,0,0,...,98000,14000,0,0,0,0,0,0,0,0
3,5233000,0,0,0,0,†,127000,2561000,0,0,...,287000,49000,0,13000,29000,0,0,10000,0,0
4,7943000,0,0,0,0,†,1094000,151000,0,0,...,4571000,177000,0,0,93000,0,0,213000,0,0
5,–,–,–,–,–,†,–,–,–,–,...,–,–,–,–,–,–,–,–,–,–
6,†,†,†,†,†,25531000,1436000,3671000,0,0,...,0,750000,0,0,2722000,0,0,0,55000,0
7,40352000,0,0,0,12145000,†,1850000,5065000,0,0,...,1847000,243000,0,47000,661000,0,0,203000,0,24000
8,14526000,0,0,0,6211000,†,35000,383000,0,0,...,354000,46000,0,0,100000,0,0,67000,0,0
9,1398000,0,0,0,0,†,0,102000,0,0,...,15000,1000,0,0,19000,0,0,3000,0,0
10,40859000,0,0,0,0,†,4298000,12978000,0,100000,...,5425000,1114000,0,217000,1348000,0,0,574000,0,0
11,15300000,0,0,0,0,†,56000,3691000,0,0,...,5916000,363000,0,0,172000,0,0,691000,0,0
12,76000,0,0,0,0,†,0,0,0,0,...,62000,6000,0,0,0,0,0,0,0,0
13,316000,0,0,0,0,†,0,15000,0,0,...,309000,18000,0,0,19000,0,0,18000,0,0
14,†,†,†,†,†,0,0,0,0,0,...,0,0,0,0,167000,0,0,0,0,0
15,1364000,0,0,0,0,†,0,4000,0,0,...,53000,11000,0,0,191000,0,203000,0,0,0
16,6292000,0,0,0,0,†,0,778000,0,39000,...,277000,69000,0,0,0,0,65000,0,20000,0
17,11976000,0,0,0,0,†,531000,2374000,0,0,...,1256000,152000,0,0,2000,0,0,41000,0,0
18,180000,0,0,0,0,†,0,0,0,0,...,503000,53000,0,0,0,0,0,35000,0,0
19,438000,0,0,0,0,†,0,38000,0,0,...,0,8000,0,0,15000,0,0,0,0,0
20,50334000,0,0,0,2118000,†,0,301000,0,0,...,7246000,680000,0,0,282000,0,0,621000,0,0
21,1072000,0,0,0,0,†,0,67000,0,0,...,167000,19000,0,0,18000,0,0,25000,0,0
22,217000,0,0,0,0,†,0,50000,0,0,...,0,11000,0,0,0,0,0,0,0,0
23,35365000,0,0,0,0,†,7714000,3190000,0,0,...,9198000,678000,0,180000,533000,0,0,771000,0,0
24,†,†,†,†,†,1110000,0,5286000,0,0,...,0,0,0,0,316000,0,0,0,0,0
25,†,†,†,†,†,†,†,†,†,†,...,†,†,†,†,†,†,†,†,†,†
26,24854000,0,0,0,0,†,0,44000,0,0,...,963000,176000,0,27000,66000,0,0,0,0,0
27,89002000,0,0,0,0,†,4228000,335000,0,0,...,372000,933000,0,0,1805000,0,0,1226000,0,128000
28,97765000,0,0,0,0,†,7587000,3304000,0,903000,...,20304000,1290000,0,608000,965000,0,0,847000,0,0
29,6366000,0,0,0,0,†,240000,910000,0,0,...,425000,75000,0,50000,43000,0,0,0,24000,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1138,302000,0,0,0,0,†,0,5000,0,0,...,0,0,0,0,14000,0,0,0,0,0
1139,4489000,0,0,0,0,†,0,124000,0,0,...,471000,109000,0,5000,53000,0,0,64000,0,0
1140,1449000,0,0,0,0,†,0,76000,0,0,...,18000,9000,0,0,19000,0,0,2000,0,0
1141,1400000,0,0,0,0,†,13000,692000,0,0,...,800000,7000,0,0,132000,0,0,24000,0,3000
1142,26087000,0,0,0,0,†,849000,5013000,0,43000,...,1022000,87000,0,39000,637000,0,0,96000,0,0
1143,690000,0,0,0,0,†,0,130000,0,0,...,93000,1000,0,0,42000,0,0,0,0,0
1144,3857000,0,0,0,0,†,274000,538000,0,0,...,493000,95000,0,16000,2000,0,0,64000,0,0
1145,778000,0,0,0,0,†,0,60000,0,0,...,1445000,114000,0,0,63000,0,0,123000,0,0
1146,15558000,0,0,0,1844000,†,1895000,24000,0,0,...,426000,31000,0,0,58000,0,0,32000,0,0
1147,3091000,0,0,0,0,†,324000,568000,0,0,...,1763000,110000,0,30000,83000,0,0,96000,0,0
1148,28653000,0,0,0,0,†,352000,3308000,114000,0,...,3739000,244000,0,70000,781000,0,0,281000,0,0
1149,8481000,0,0,0,302000,†,9229000,0,0,0,...,7000,6000,0,0,0,0,0,0,0,0
1150,240000,0,0,0,0,†,11000,99000,0,0,...,401000,62000,0,0,145000,0,0,27000,0,0
1151,5725000,0,0,0,0,†,244000,722000,0,0,...,693000,29000,0,0,55000,0,0,75000,0,0
1152,†,†,†,†,†,8264000,769000,2595000,0,0,...,164000,400000,0,0,289000,0,0,30000,0,3760000
1153,†,†,†,†,†,†,†,†,†,†,...,†,†,†,†,†,†,†,†,†,†
1154,†,†,†,†,†,†,†,†,†,†,...,†,†,†,†,†,†,†,†,†,†
1155,8308000,0,0,0,0,†,0,668000,0,0,...,391000,0,0,27000,98000,0,0,0,0,0
1156,2223000,0,0,0,0,†,134000,368000,0,0,...,447000,41000,0,0,304000,0,0,0,0,0
1157,2888000,0,0,0,0,†,0,666000,0,0,...,112000,25000,0,26000,164000,0,0,0,11000,0
1158,28556000,0,0,0,5202000,†,67000,3200000,0,30000,...,5493000,392000,0,98000,264000,0,0,259000,0,349000
1159,†,†,†,†,†,2764000,7000,4828000,0,0,...,0,0,0,0,1599000,0,0,34000,0,0
1160,13659000,0,0,0,1373000,†,944000,4907000,10000,0,...,2753000,193000,0,54000,242000,0,0,80000,0,0
1161,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1162,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1163,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1164,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1165,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1166,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1167,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [12]:
# see all columns of all_revenue 

all_revenue.columns

Index(['Local_Property Taxes', 'Local_General Sales Taxes',
       'Local_Public Utility Taxes', 'Local_Individual_and_Corp_Income Taex',
       'Local_All Other Taxes', 'Local_Parent Government Contributions',
       'Local_Revenue_Cities and Counties', 'Local_Other School Systems',
       'Local_Tuition Fees_Pupils and Parents',
       'Local_Transp_ Fees_Pupils and Parents', 'Local_School Lunch Revenues',
       'Local_Textbook Sales and Rentals', 'Local_Student Activity Receipts',
       'Local_Other Sales and Service Rev', 'Local_Student Fees NonSpecified',
       'Local_Interest Earnings', 'Local_Miscellaneous Other Local Rev',
       'Local_Special Processing', 'Local_Rents and Royalties',
       'Local_Sale of Property', 'Local_Fines and Forfeits',
       'Local_Private Contributions', 'State_General Formula Assistance',
       'State_Special Education Programs', 'State_Transportation Programs',
       'State_Staff Improvement Programs',
       'State_Compensat and Basic Skills Prog',
       'State_Vocational Education Programs',
       'State_Capital Outlay and Debt ServProg',
       'State_Bilingual Education Programs',
       'State_Gifted and Talented Programs', 'State_School Lunch Programs',
       'State_All Other Rev', 'State_Payment for LEA Empl_Benefits',
       'State_Other State Payments', 'State_Non-Specified',
       'Federal_Federal Title I Revenue', 'Federal_Children with Disabilities',
       'Federal_Child Nutrition Act', 'Federal_ Eisenhower Math and Science',
       'Federal_Drug_Free_Schools', 'Federal_Vocational Education',
       'Federal_ All Other Fed_Aid Through State', 'Federal_Nonspecified',
       'Federal_Impact Aid', 'Federal_Bilingual Education',
       'Federal_Native American', 'Federal_All Other Federal Aid'],
      dtype='object')

In [13]:
# transform string values into numeric values - it modifies non numeric values to NaNs

all_revenue_df = all_revenue.apply(pd.to_numeric, errors='coerce')
all_revenue_df.head(10)

,Local_Property Taxes,Local_General Sales Taxes,Local_Public Utility Taxes,Local_Individual_and_Corp_Income Taex,Local_All Other Taxes,Local_Parent Government Contributions,Local_Revenue_Cities and Counties,Local_Other School Systems,Local_Tuition Fees_Pupils and Parents,Local_Transp_ Fees_Pupils and Parents,...,Federal_Child Nutrition Act,Federal_ Eisenhower Math and Science,Federal_Drug_Free_Schools,Federal_Vocational Education,Federal_ All Other Fed_Aid Through State,Federal_Nonspecified,Federal_Impact Aid,Federal_Bilingual Education,Federal_Native American,Federal_All Other Federal Aid
0,32494000.0,0.0,0.0,0.0,0.0,NaN,7880000.0,2725000.0,1153000.0,0.0,...,6058000.0,1140000.0,483000.0,210000.0,2284000.0,0.0,0.0,316000.0,0.0,0.0
1,53504000.0,0.0,0.0,0.0,10444000.0,NaN,1198000.0,2146000.0,557000.0,0.0,...,130000.0,75000.0,0.0,47000.0,68000.0,0.0,0.0,7000.0,0.0,0.0
2,1276000.0,0.0,0.0,0.0,0.0,NaN,40000.0,156000.0,0.0,0.0,...,98000.0,14000.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,5233000.0,0.0,0.0,0.0,0.0,NaN,127000.0,2561000.0,0.0,0.0,...,287000.0,49000.0,0.0,13000.0,29000.0,0.0,0.0,10000.0,0.0,0.0
4,7943000.0,0.0,0.0,0.0,0.0,NaN,1094000.0,151000.0,0.0,0.0,...,4571000.0,177000.0,0.0,0.0,93000.0,0.0,0.0,213000.0,0.0,0.0
5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,NaN,NaN,NaN,NaN,NaN,25531000.0,1436000.0,3671000.0,0.0,0.0,...,0.0,750000.0,0.0,0.0,2722000.0,0.0,0.0,0.0,55000.0,0.0
7,40352000.0,0.0,0.0,0.0,12145000.0,NaN,1850000.0,5065000.0,0.0,0.0,...,1847000.0,243000.0,0.0,47000.0,661000.0,0.0,0.0,203000.0,0.0,24000.0
8,14526000.0,0.0,0.0,0.0,6211000.0,NaN,35000.0,383000.0,0.0,0.0,...,354000.0,46000.0,0.0,0.0,100000.0,0.0,0.0,67000.0,0.0,0.0
9,1398000.0,0.0,0.0,0.0,0.0,NaN,0.0,102000.0,0.0,0.0,...,15000.0,1000.0,0.0,0.0,19000.0,0.0,0.0,3000.0,0.0,0.0

In [15]:
# Adding the column containing total local revenue to the all_revenue_df

all_revenue_df['Total Local Revenue'] = all_revenue_df.iloc[:, 2:24].sum(axis=1)
all_revenue_df['Total Local Revenue']

0       171312000.0
1        27481000.0
2         3714000.0
3        25820000.0
4        96654000.0
5               0.0
6        40170000.0
7        76372000.0
8        45387000.0
9          759000.0
10      149777000.0
11       83568000.0
12         871000.0
13        3832000.0
14        1108000.0
15         888000.0
16       10410000.0
17       45511000.0
18        5325000.0
19         566000.0
20       81282000.0
21        2466000.0
22        1532000.0
23      169894000.0
24       10585000.0
25              0.0
26       10336000.0
27      116382000.0
28      252912000.0
29       13268000.0
           ...
1138        41000.0
1139      9741000.0
1140       690000.0
1141     12515000.0
1142     31197000.0
1143      1988000.0
1144     12564000.0
1145     18820000.0
1146     29619000.0
1147     22755000.0
1148     73105000.0
1149     13675000.0
1150      4503000.0
1151     12155000.0
1152     28171000.0
1153            0.0
1154            0.0
1155     12881000.0
1156      6935000.0
1157      4993000.0
1158    102837000.0
1159     20818000.0
1160     73160000.0
1161            0.0
1162            0.0
1163            0.0
1164            0.0
1165            0.0
1166            0.0
1167            0.0
Name: Total Local Revenue, Length: 1168, dtype: float64

In [16]:
# checking to see if the new column was added

all_revenue_df.head(10)

,Local_Property Taxes,Local_General Sales Taxes,Local_Public Utility Taxes,Local_Individual_and_Corp_Income Taex,Local_All Other Taxes,Local_Parent Government Contributions,Local_Revenue_Cities and Counties,Local_Other School Systems,Local_Tuition Fees_Pupils and Parents,Local_Transp_ Fees_Pupils and Parents,...,Federal_ Eisenhower Math and Science,Federal_Drug_Free_Schools,Federal_Vocational Education,Federal_ All Other Fed_Aid Through State,Federal_Nonspecified,Federal_Impact Aid,Federal_Bilingual Education,Federal_Native American,Federal_All Other Federal Aid,Total Local Revenue
0,32494000.0,0.0,0.0,0.0,0.0,NaN,7880000.0,2725000.0,1153000.0,0.0,...,1140000.0,483000.0,210000.0,2284000.0,0.0,0.0,316000.0,0.0,0.0,171312000.0
1,53504000.0,0.0,0.0,0.0,10444000.0,NaN,1198000.0,2146000.0,557000.0,0.0,...,75000.0,0.0,47000.0,68000.0,0.0,0.0,7000.0,0.0,0.0,27481000.0
2,1276000.0,0.0,0.0,0.0,0.0,NaN,40000.0,156000.0,0.0,0.0,...,14000.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,3714000.0
3,5233000.0,0.0,0.0,0.0,0.0,NaN,127000.0,2561000.0,0.0,0.0,...,49000.0,0.0,13000.0,29000.0,0.0,0.0,10000.0,0.0,0.0,25820000.0
4,7943000.0,0.0,0.0,0.0,0.0,NaN,1094000.0,151000.0,0.0,0.0,...,177000.0,0.0,0.0,93000.0,0.0,0.0,213000.0,0.0,0.0,96654000.0
5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0
6,NaN,NaN,NaN,NaN,NaN,25531000.0,1436000.0,3671000.0,0.0,0.0,...,750000.0,0.0,0.0,2722000.0,0.0,0.0,0.0,55000.0,0.0,40170000.0
7,40352000.0,0.0,0.0,0.0,12145000.0,NaN,1850000.0,5065000.0,0.0,0.0,...,243000.0,0.0,47000.0,661000.0,0.0,0.0,203000.0,0.0,24000.0,76372000.0
8,14526000.0,0.0,0.0,0.0,6211000.0,NaN,35000.0,383000.0,0.0,0.0,...,46000.0,0.0,0.0,100000.0,0.0,0.0,67000.0,0.0,0.0,45387000.0
9,1398000.0,0.0,0.0,0.0,0.0,NaN,0.0,102000.0,0.0,0.0,...,1000.0,0.0,0.0,19000.0,0.0,0.0,3000.0,0.0,0.0,759000.0

In [17]:
# Selecting the state columns

state = all_revenue_df.iloc[:, 24:36]
state.columns

Index(['State_Transportation Programs', 'State_Staff Improvement Programs',
       'State_Compensat and Basic Skills Prog',
       'State_Vocational Education Programs',
       'State_Capital Outlay and Debt ServProg',
       'State_Bilingual Education Programs',
       'State_Gifted and Talented Programs', 'State_School Lunch Programs',
       'State_All Other Rev', 'State_Payment for LEA Empl_Benefits',
       'State_Other State Payments', 'State_Non-Specified'],
      dtype='object')

In [18]:
# Adding new column to the dataframe with the total revenue per state

all_revenue_df['Total State Revenue'] = all_revenue_df.iloc[:, 24:36].sum(axis=1)

In [19]:
all_revenue_df.head(10)

,Local_Property Taxes,Local_General Sales Taxes,Local_Public Utility Taxes,Local_Individual_and_Corp_Income Taex,Local_All Other Taxes,Local_Parent Government Contributions,Local_Revenue_Cities and Counties,Local_Other School Systems,Local_Tuition Fees_Pupils and Parents,Local_Transp_ Fees_Pupils and Parents,...,Federal_Drug_Free_Schools,Federal_Vocational Education,Federal_ All Other Fed_Aid Through State,Federal_Nonspecified,Federal_Impact Aid,Federal_Bilingual Education,Federal_Native American,Federal_All Other Federal Aid,Total Local Revenue,Total State Revenue
0,32494000.0,0.0,0.0,0.0,0.0,NaN,7880000.0,2725000.0,1153000.0,0.0,...,483000.0,210000.0,2284000.0,0.0,0.0,316000.0,0.0,0.0,171312000.0,39046000.0
1,53504000.0,0.0,0.0,0.0,10444000.0,NaN,1198000.0,2146000.0,557000.0,0.0,...,0.0,47000.0,68000.0,0.0,0.0,7000.0,0.0,0.0,27481000.0,8624000.0
2,1276000.0,0.0,0.0,0.0,0.0,NaN,40000.0,156000.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,3714000.0,473000.0
3,5233000.0,0.0,0.0,0.0,0.0,NaN,127000.0,2561000.0,0.0,0.0,...,0.0,13000.0,29000.0,0.0,0.0,10000.0,0.0,0.0,25820000.0,2913000.0
4,7943000.0,0.0,0.0,0.0,0.0,NaN,1094000.0,151000.0,0.0,0.0,...,0.0,0.0,93000.0,0.0,0.0,213000.0,0.0,0.0,96654000.0,12463000.0
5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0
6,NaN,NaN,NaN,NaN,NaN,25531000.0,1436000.0,3671000.0,0.0,0.0,...,0.0,0.0,2722000.0,0.0,0.0,0.0,55000.0,0.0,40170000.0,9711000.0
7,40352000.0,0.0,0.0,0.0,12145000.0,NaN,1850000.0,5065000.0,0.0,0.0,...,0.0,47000.0,661000.0,0.0,0.0,203000.0,0.0,24000.0,76372000.0,14285000.0
8,14526000.0,0.0,0.0,0.0,6211000.0,NaN,35000.0,383000.0,0.0,0.0,...,0.0,0.0,100000.0,0.0,0.0,67000.0,0.0,0.0,45387000.0,6761000.0
9,1398000.0,0.0,0.0,0.0,0.0,NaN,0.0,102000.0,0.0,0.0,...,0.0,0.0,19000.0,0.0,0.0,3000.0,0.0,0.0,759000.0,303000.0

In [20]:
# selecting the federal columns

federal = all_revenue_df.iloc[:, 36:-2]
federal.columns

Index(['Federal_Federal Title I Revenue', 'Federal_Children with Disabilities',
       'Federal_Child Nutrition Act', 'Federal_ Eisenhower Math and Science',
       'Federal_Drug_Free_Schools', 'Federal_Vocational Education',
       'Federal_ All Other Fed_Aid Through State', 'Federal_Nonspecified',
       'Federal_Impact Aid', 'Federal_Bilingual Education',
       'Federal_Native American', 'Federal_All Other Federal Aid'],
      dtype='object')

In [21]:
# Adding new column to the dataframe with the total federal revenue

all_revenue_df['Total Federal Revenue'] = all_revenue_df.iloc[:, 36:-2].sum(axis=1)
all_revenue_df

,Local_Property Taxes,Local_General Sales Taxes,Local_Public Utility Taxes,Local_Individual_and_Corp_Income Taex,Local_All Other Taxes,Local_Parent Government Contributions,Local_Revenue_Cities and Counties,Local_Other School Systems,Local_Tuition Fees_Pupils and Parents,Local_Transp_ Fees_Pupils and Parents,...,Federal_Vocational Education,Federal_ All Other Fed_Aid Through State,Federal_Nonspecified,Federal_Impact Aid,Federal_Bilingual Education,Federal_Native American,Federal_All Other Federal Aid,Total Local Revenue,Total State Revenue,Total Federal Revenue
0,32494000.0,0.0,0.0,0.0,0.0,NaN,7880000.0,2725000.0,1153000.0,0.0,...,210000.0,2284000.0,0.0,0.0,316000.0,0.0,0.0,171312000.0,39046000.0,15893000.0
1,53504000.0,0.0,0.0,0.0,10444000.0,NaN,1198000.0,2146000.0,557000.0,0.0,...,47000.0,68000.0,0.0,0.0,7000.0,0.0,0.0,27481000.0,8624000.0,1605000.0
2,1276000.0,0.0,0.0,0.0,0.0,NaN,40000.0,156000.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,3714000.0,473000.0,223000.0
3,5233000.0,0.0,0.0,0.0,0.0,NaN,127000.0,2561000.0,0.0,0.0,...,13000.0,29000.0,0.0,0.0,10000.0,0.0,0.0,25820000.0,2913000.0,1250000.0
4,7943000.0,0.0,0.0,0.0,0.0,NaN,1094000.0,151000.0,0.0,0.0,...,0.0,93000.0,0.0,0.0,213000.0,0.0,0.0,96654000.0,12463000.0,10906000.0
5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0
6,NaN,NaN,NaN,NaN,NaN,25531000.0,1436000.0,3671000.0,0.0,0.0,...,0.0,2722000.0,0.0,0.0,0.0,55000.0,0.0,40170000.0,9711000.0,5914000.0
7,40352000.0,0.0,0.0,0.0,12145000.0,NaN,1850000.0,5065000.0,0.0,0.0,...,47000.0,661000.0,0.0,0.0,203000.0,0.0,24000.0,76372000.0,14285000.0,5985000.0
8,14526000.0,0.0,0.0,0.0,6211000.0,NaN,35000.0,383000.0,0.0,0.0,...,0.0,100000.0,0.0,0.0,67000.0,0.0,0.0,45387000.0,6761000.0,6063000.0
9,1398000.0,0.0,0.0,0.0,0.0,NaN,0.0,102000.0,0.0,0.0,...,0.0,19000.0,0.0,0.0,3000.0,0.0,0.0,759000.0,303000.0,61000.0
10,40859000.0,0.0,0.0,0.0,0.0,NaN,4298000.0,12978000.0,0.0,100000.0,...,217000.0,1348000.0,0.0,0.0,574000.0,0.0,0.0,149777000.0,69201000.0,31160000.0
11,15300000.0,0.0,0.0,0.0,0.0,NaN,56000.0,3691000.0,0.0,0.0,...,0.0,172000.0,0.0,0.0,691000.0,0.0,0.0,83568000.0,13610000.0,12363000.0
12,76000.0,0.0,0.0,0.0,0.0,NaN,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,871000.0,116000.0,118000.0
13,316000.0,0.0,0.0,0.0,0.0,NaN,0.0,15000.0,0.0,0.0,...,0.0,19000.0,0.0,0.0,18000.0,0.0,0.0,3832000.0,565000.0,624000.0
14,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,...,0.0,167000.0,0.0,0.0,0.0,0.0,0.0,1108000.0,172000.0,167000.0
15,1364000.0,0.0,0.0,0.0,0.0,NaN,0.0,4000.0,0.0,0.0,...,0.0,191000.0,0.0,203000.0,0.0,0.0,0.0,888000.0,308000.0,518000.0
16,6292000.0,0.0,0.0,0.0,0.0,NaN,0.0,778000.0,0.0,39000.0,...,0.0,0.0,0.0,65000.0,0.0,20000.0,0.0,10410000.0,2122000.0,901000.0
17,11976000.0,0.0,0.0,0.0,0.0,NaN,531000.0,2374000.0,0.0,0.0,...,0.0,2000.0,0.0,0.0,41000.0,0.0,0.0,45511000.0,6821000.0,2777000.0
18,180000.0,0.0,0.0,0.0,0.0,NaN,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,35000.0,0.0,0.0,5325000.0,783000.0,995000.0
19,438000.0,0.0,0.0,0.0,0.0,NaN,0.0,38000.0,0.0,0.0,...,0.0,15000.0,0.0,0.0,0.0,0.0,0.0,566000.0,133000.0,95000.0
20,50334000.0,0.0,0.0,0.0,2118000.0,NaN,0.0,301000.0,0.0,0.0,...,0.0,282000.0,0.0,0.0,621000.0,0.0,0.0,81282000.0,17682000.0,14255000.0
21,1072000.0,0.0,0.0,0.0,0.0,NaN,0.0,67000.0,0.0,0.0,...,0.0,18000.0,0.0,0.0,25000.0,0.0,0.0,2466000.0,487000.0,399000.0
22,217000.0,0.0,0.0,0.0,0.0,NaN,0.0,50000.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1532000.0,136000.0,101000.0
23,35365000.0,0.0,0.0,0.0,0.0,NaN,7714000.0,3190000.0,0.0,0.0,...,180000.0,533000.0,0.0,0.0,771000.0,0.0,0.0,169894000.0,32776000.0,19938000.0
24,NaN,NaN,NaN,NaN,NaN,1110000.0,0.0,5286000.0,0.0,0.0,...,0.0,316000.0,0.0,0.0,0.0,0.0,0.0,10585000.0,1079000.0,1195000.0
25,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0
26,24854000.0,0.0,0.0,0.0,0.0,NaN,0.0,44000.0,0.0,0.0,...,27000.0,66000.0,0.0,0.0,0.0,0.0,0.0,10336000.0,5267000.0,1912000.0
27,89002000.0,0.0,0.0,0.0,0.0,NaN,4228000.0,335000.0,0.0,0.0,...,0.0,1805000.0,0.0,0.0,1226000.0,0.0,128000.0,116382000.0,33643000.0,14690000.0
28,97765000.0,0.0,0.0,0.0,0.0,NaN,7587000.0,3304000.0,0.0,903000.0,...,608000.0,965000.0,0.0,0.0,847000.0,0.0,0.0,252912000.0,58792000.0,38103000.0
29,6366000.0,0.0,0.0,0.0,0.0,NaN,240000.0,910000.0,0.0,0.0,...,50000.0,43000.0,0.0,0.0,0.0,24000.0,0.0,13268000.0,2939000.0,1531000.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1138,302000.0,0.0,0.0,0.0,0.0,NaN,0.0,5000.0,0.0,0.0,...,0.0,14000.0,0.0,0.0,0.0,0.0,0.0,41000.0,22000.0,17000.0
1139,4489000.0,0.0,0.0,0.0,0.0,NaN,0.0,124000.0,0.0,0.0,...,5000.0,53000.0,0.0,0.0,64000.0,0.0,0.0,9741000.0,1553000.0,1062000.0
1140,1449000.0,0.0,0.0,0.0,0.0,NaN,0.0,76000.0,0.0,0.0,...,0.0,19000.0,0.0,0.0,2000.0,0.0,0.0,690000.0,407000.0,129000.0
1141,1400000.0,0.0,0.0,0.0,0.0,NaN,13000.0,692000.0,0.0,0.0,...,0.0,132000.0,0.0,0.0,24000.0,0.0,3000.0,12515000.0,1838000.0,1868000.0
1142,26087000.0,0.0,0.0,0.0,0.0,NaN,849000.0,5013000.0,0.0,43000.0,...,39000.0,637000.0,0.0,0.0,96000.0,0.0,0.0,31197000.0,6964000.0,3400000.0
1143,690000.0,0.0,0.0,0.0,0.0,NaN,0.0,130000.0,0.0,0.0,...,0.0,42000.0,0.0,0.0,0.0,0.0,0.0,1988000.0,337000.0,164000.0
1144,3857000.0,0.0,0.0,0.0,0.0,NaN,274000.0,538000.0,0.0,0.0,...,16000.0,2000.0,0.0,0.0,64000.0,0.0,0.0,12564000.0,2567000.0,1208000.0
1145,778000.0,0.0,0.0,0.0,0.0,NaN,0.0,60000.0,0.0,0.0,...,0.0,63000.0,0.0,0.0,123000.0,0.0,0.0,18820000.0,3615000.0,3040000.0
1146,15558000.0,0.0,0.0,0.0,1844000.0,NaN,1895000.0,24000.0,0.0,0.0,...,0.0,58000.0,0.0,0.0,32000.0,0.0,0.0,29619000.0,35763000.0,954000.0
1147,3091000.0,0.0,0.0,0.0,0.0,NaN,324000.0,568000.0,0.0,0.0,...,30000.0,83000.0,0.0,0.0,96000.0,0.0,0.0,22755000.0,4715000.0,3370000.0
1148,28653000.0,0.0,0.0,0.0,0.0,NaN,352000.0,3308000.0,114000.0,0.0,...,70000.0,781000.0,0.0,0.0,281000.0,0.0,0.0,73105000.0,15635000.0,8440000.0
1149,8481000.0,0.0,0.0,0.0,302000.0,NaN,9229000.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,13675000.0,865000.0,96000.0
1150,240000.0,0.0,0.0,0.0,0.0,NaN,11000.0,99000.0,0.0,0.0,...,0.0,145000.0,0.0,0.0,27000.0,0.0,0.0,4503000.0,690000.0,1144000.0
1151,5725000.0,0.0,0.0,0.0,0.0,NaN,244000.0,722000.0,0.0,0.0,...,0.0,55000.0,0.0,0.0,75000.0,0.0,0.0,12155000.0,2300000.0,1360000.0
1152,NaN,NaN,NaN,NaN,NaN,8264000.0,769000.0,2595000.0,0.0,0.0,...,0.0,289000.0,0.0,0.0,30000.0,0.0,3760000.0,28171000.0,3974000.0,10773000.0
1153,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0
1154,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0
1155,8308000.0,0.0,0.0,0.0,0.0,NaN,0.0,668000.0,0.0,0.0,...,27000.0,98000.0,0.0,0.0,0.0,0.0,0.0,12881000.0,3060000.0,1278000.0
1156,2223000.0,0.0,0.0,0.0,0.0,NaN,134000.0,368000.0,0.0,0.0,...,0.0,304000.0,0.0,0.0,0.0,0.0,0.0,6935000.0,1028000.0,1473000.0
1157,2888000.0,0.0,0.0,0.0,0.0,NaN,0.0,666000.0,0.0,0.0,...,26000.0,164000.0,0.0,0.0,0.0,11000.0,0.0,4993000.0,1205000.0,638000.0
1158,28556000.0,0.0,0.0,0.0,5202000.0,NaN,67000.0,3200000.0,0.0,30000.0,...,98000.0,264000.0,0.0,0.0,259000.0,0.0,349000.0,102837000.0,22711000.0,11731000.0
1159,NaN,NaN,NaN,NaN,NaN,2764000.0,7000.0,4828000.0,0.0,0.0,...,0.0,1599000.0,0.0,0.0,34000.0,0.0,0.0,20818000.0,3279000.0,5200000.0
1160,13659000.0,0.0,0.0,0.0,1373000.0,NaN,944000.0,4907000.0,10000.0,0.0,...,54000.0,242000.0,0.0,0.0,80000.0,0.0,0.0,73160000.0,13339000.0,7105000.0
1161,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0
1162,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0
1163,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0
1164,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0
1165,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0
1166,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0
1167,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0

In [22]:
all_revenue_df['Total Revenue'] = all_revenue_df.iloc[:, -3:].sum(axis=1)
all_revenue_df

,Local_Property Taxes,Local_General Sales Taxes,Local_Public Utility Taxes,Local_Individual_and_Corp_Income Taex,Local_All Other Taxes,Local_Parent Government Contributions,Local_Revenue_Cities and Counties,Local_Other School Systems,Local_Tuition Fees_Pupils and Parents,Local_Transp_ Fees_Pupils and Parents,...,Federal_ All Other Fed_Aid Through State,Federal_Nonspecified,Federal_Impact Aid,Federal_Bilingual Education,Federal_Native American,Federal_All Other Federal Aid,Total Local Revenue,Total State Revenue,Total Federal Revenue,Total Revenue
0,32494000.0,0.0,0.0,0.0,0.0,NaN,7880000.0,2725000.0,1153000.0,0.0,...,2284000.0,0.0,0.0,316000.0,0.0,0.0,171312000.0,39046000.0,15893000.0,226251000.0
1,53504000.0,0.0,0.0,0.0,10444000.0,NaN,1198000.0,2146000.0,557000.0,0.0,...,68000.0,0.0,0.0,7000.0,0.0,0.0,27481000.0,8624000.0,1605000.0,37710000.0
2,1276000.0,0.0,0.0,0.0,0.0,NaN,40000.0,156000.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,3714000.0,473000.0,223000.0,4410000.0
3,5233000.0,0.0,0.0,0.0,0.0,NaN,127000.0,2561000.0,0.0,0.0,...,29000.0,0.0,0.0,10000.0,0.0,0.0,25820000.0,2913000.0,1250000.0,29983000.0
4,7943000.0,0.0,0.0,0.0,0.0,NaN,1094000.0,151000.0,0.0,0.0,...,93000.0,0.0,0.0,213000.0,0.0,0.0,96654000.0,12463000.0,10906000.0,120023000.0
5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0
6,NaN,NaN,NaN,NaN,NaN,25531000.0,1436000.0,3671000.0,0.0,0.0,...,2722000.0,0.0,0.0,0.0,55000.0,0.0,40170000.0,9711000.0,5914000.0,55795000.0
7,40352000.0,0.0,0.0,0.0,12145000.0,NaN,1850000.0,5065000.0,0.0,0.0,...,661000.0,0.0,0.0,203000.0,0.0,24000.0,76372000.0,14285000.0,5985000.0,96642000.0
8,14526000.0,0.0,0.0,0.0,6211000.0,NaN,35000.0,383000.0,0.0,0.0,...,100000.0,0.0,0.0,67000.0,0.0,0.0,45387000.0,6761000.0,6063000.0,58211000.0
9,1398000.0,0.0,0.0,0.0,0.0,NaN,0.0,102000.0,0.0,0.0,...,19000.0,0.0,0.0,3000.0,0.0,0.0,759000.0,303000.0,61000.0,1123000.0
10,40859000.0,0.0,0.0,0.0,0.0,NaN,4298000.0,12978000.0,0.0,100000.0,...,1348000.0,0.0,0.0,574000.0,0.0,0.0,149777000.0,69201000.0,31160000.0,250138000.0
11,15300000.0,0.0,0.0,0.0,0.0,NaN,56000.0,3691000.0,0.0,0.0,...,172000.0,0.0,0.0,691000.0,0.0,0.0,83568000.0,13610000.0,12363000.0,109541000.0
12,76000.0,0.0,0.0,0.0,0.0,NaN,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,871000.0,116000.0,118000.0,1105000.0
13,316000.0,0.0,0.0,0.0,0.0,NaN,0.0,15000.0,0.0,0.0,...,19000.0,0.0,0.0,18000.0,0.0,0.0,3832000.0,565000.0,624000.0,5021000.0
14,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,...,167000.0,0.0,0.0,0.0,0.0,0.0,1108000.0,172000.0,167000.0,1447000.0
15,1364000.0,0.0,0.0,0.0,0.0,NaN,0.0,4000.0,0.0,0.0,...,191000.0,0.0,203000.0,0.0,0.0,0.0,888000.0,308000.0,518000.0,1714000.0
16,6292000.0,0.0,0.0,0.0,0.0,NaN,0.0,778000.0,0.0,39000.0,...,0.0,0.0,65000.0,0.0,20000.0,0.0,10410000.0,2122000.0,901000.0,13433000.0
17,11976000.0,0.0,0.0,0.0,0.0,NaN,531000.0,2374000.0,0.0,0.0,...,2000.0,0.0,0.0,41000.0,0.0,0.0,45511000.0,6821000.0,2777000.0,55109000.0
18,180000.0,0.0,0.0,0.0,0.0,NaN,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,35000.0,0.0,0.0,5325000.0,783000.0,995000.0,7103000.0
19,438000.0,0.0,0.0,0.0,0.0,NaN,0.0,38000.0,0.0,0.0,...,15000.0,0.0,0.0,0.0,0.0,0.0,566000.0,133000.0,95000.0,794000.0
20,50334000.0,0.0,0.0,0.0,2118000.0,NaN,0.0,301000.0,0.0,0.0,...,282000.0,0.0,0.0,621000.0,0.0,0.0,81282000.0,17682000.0,14255000.0,113219000.0
21,1072000.0,0.0,0.0,0.0,0.0,NaN,0.0,67000.0,0.0,0.0,...,18000.0,0.0,0.0,25000.0,0.0,0.0,2466000.0,487000.0,399000.0,3352000.0
22,217000.0,0.0,0.0,0.0,0.0,NaN,0.0,50000.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1532000.0,136000.0,101000.0,1769000.0
23,35365000.0,0.0,0.0,0.0,0.0,NaN,7714000.0,3190000.0,0.0,0.0,...,533000.0,0.0,0.0,771000.0,0.0,0.0,169894000.0,32776000.0,19938000.0,222608000.0
24,NaN,NaN,NaN,NaN,NaN,1110000.0,0.0,5286000.0,0.0,0.0,...,316000.0,0.0,0.0,0.0,0.0,0.0,10585000.0,1079000.0,1195000.0,12859000.0
25,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0
26,24854000.0,0.0,0.0,0.0,0.0,NaN,0.0,44000.0,0.0,0.0,...,66000.0,0.0,0.0,0.0,0.0,0.0,10336000.0,5267000.0,1912000.0,17515000.0
27,89002000.0,0.0,0.0,0.0,0.0,NaN,4228000.0,335000.0,0.0,0.0,...,1805000.0,0.0,0.0,1226000.0,0.0,128000.0,116382000.0,33643000.0,14690000.0,164715000.0
28,97765000.0,0.0,0.0,0.0,0.0,NaN,7587000.0,3304000.0,0.0,903000.0,...,965000.0,0.0,0.0,847000.0,0.0,0.0,252912000.0,58792000.0,38103000.0,349807000.0
29,6366000.0,0.0,0.0,0.0,0.0,NaN,240000.0,910000.0,0.0,0.0,...,43000.0,0.0,0.0,0.0,24000.0,0.0,13268000.0,2939000.0,1531000.0,17738000.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1138,302000.0,0.0,0.0,0.0,0.0,NaN,0.0,5000.0,0.0,0.0,...,14000.0,0.0,0.0,0.0,0.0,0.0,41000.0,22000.0,17000.0,80000.0
1139,4489000.0,0.0,0.0,0.0,0.0,NaN,0.0,124000.0,0.0,0.0,...,53000.0,0.0,0.0,64000.0,0.0,0.0,9741000.0,1553000.0,1062000.0,12356000.0
1140,1449000.0,0.0,0.0,0.0,0.0,NaN,0.0,76000.0,0.0,0.0,...,19000.0,0.0,0.0,2000.0,0.0,0.0,690000.0,407000.0,129000.0,1226000.0
1141,1400000.0,0.0,0.0,0.0,0.0,NaN,13000.0,692000.0,0.0,0.0,...,132000.0,0.0,0.0,24000.0,0.0,3000.0,12515000.0,1838000.0,1868000.0,16221000.0
1142,26087000.0,0.0,0.0,0.0,0.0,NaN,849000.0,5013000.0,0.0,43000.0,...,637000.0,0.0,0.0,96000.0,0.0,0.0,31197000.0,6964000.0,3400000.0,41561000.0
1143,690000.0,0.0,0.0,0.0,0.0,NaN,0.0,130000.0,0.0,0.0,...,42000.0,0.0,0.0,0.0,0.0,0.0,1988000.0,337000.0,164000.0,2489000.0
1144,3857000.0,0.0,0.0,0.0,0.0,NaN,274000.0,538000.0,0.0,0.0,...,2000.0,0.0,0.0,64000.0,0.0,0.0,12564000.0,2567000.0,1208000.0,16339000.0
1145,778000.0,0.0,0.0,0.0,0.0,NaN,0.0,60000.0,0.0,0.0,...,63000.0,0.0,0.0,123000.0,0.0,0.0,18820000.0,3615000.0,3040000.0,25475000.0
1146,15558000.0,0.0,0.0,0.0,1844000.0,NaN,1895000.0,24000.0,0.0,0.0,...,58000.0,0.0,0.0,32000.0,0.0,0.0,29619000.0,35763000.0,954000.0,66336000.0
1147,3091000.0,0.0,0.0,0.0,0.0,NaN,324000.0,568000.0,0.0,0.0,...,83000.0,0.0,0.0,96000.0,0.0,0.0,22755000.0,4715000.0,3370000.0,30840000.0
1148,28653000.0,0.0,0.0,0.0,0.0,NaN,352000.0,3308000.0,114000.0,0.0,...,781000.0,0.0,0.0,281000.0,0.0,0.0,73105000.0,15635000.0,8440000.0,97180000.0
1149,8481000.0,0.0,0.0,0.0,302000.0,NaN,9229000.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,13675000.0,865000.0,96000.0,14636000.0
1150,240000.0,0.0,0.0,0.0,0.0,NaN,11000.0,99000.0,0.0,0.0,...,145000.0,0.0,0.0,27000.0,0.0,0.0,4503000.0,690000.0,1144000.0,6337000.0
1151,5725000.0,0.0,0.0,0.0,0.0,NaN,244000.0,722000.0,0.0,0.0,...,55000.0,0.0,0.0,75000.0,0.0,0.0,12155000.0,2300000.0,1360000.0,15815000.0
1152,NaN,NaN,NaN,NaN,NaN,8264000.0,769000.0,2595000.0,0.0,0.0,...,289000.0,0.0,0.0,30000.0,0.0,3760000.0,28171000.0,3974000.0,10773000.0,42918000.0
1153,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0
1154,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0
1155,8308000.0,0.0,0.0,0.0,0.0,NaN,0.0,668000.0,0.0,0.0,...,98000.0,0.0,0.0,0.0,0.0,0.0,12881000.0,3060000.0,1278000.0,17219000.0
1156,2223000.0,0.0,0.0,0.0,0.0,NaN,134000.0,368000.0,0.0,0.0,...,304000.0,0.0,0.0,0.0,0.0,0.0,6935000.0,1028000.0,1473000.0,9436000.0
1157,2888000.0,0.0,0.0,0.0,0.0,NaN,0.0,666000.0,0.0,0.0,...,164000.0,0.0,0.0,0.0,11000.0,0.0,4993000.0,1205000.0,638000.0,6836000.0
1158,28556000.0,0.0,0.0,0.0,5202000.0,NaN,67000.0,3200000.0,0.0,30000.0,...,264000.0,0.0,0.0,259000.0,0.0,349000.0,102837000.0,22711000.0,11731000.0,137279000.0
1159,NaN,NaN,NaN,NaN,NaN,2764000.0,7000.0,4828000.0,0.0,0.0,...,1599000.0,0.0,0.0,34000.0,0.0,0.0,20818000.0,3279000.0,5200000.0,29297000.0
1160,13659000.0,0.0,0.0,0.0,1373000.0,NaN,944000.0,4907000.0,10000.0,0.0,...,242000.0,0.0,0.0,80000.0,0.0,0.0,73160000.0,13339000.0,7105000.0,93604000.0
1161,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0
1162,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0
1163,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0
1164,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0
1165,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0
1166,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0
1167,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0

In [23]:
all_revenue_df.columns

Index(['Local_Property Taxes', 'Local_General Sales Taxes',
       'Local_Public Utility Taxes', 'Local_Individual_and_Corp_Income Taex',
       'Local_All Other Taxes', 'Local_Parent Government Contributions',
       'Local_Revenue_Cities and Counties', 'Local_Other School Systems',
       'Local_Tuition Fees_Pupils and Parents',
       'Local_Transp_ Fees_Pupils and Parents', 'Local_School Lunch Revenues',
       'Local_Textbook Sales and Rentals', 'Local_Student Activity Receipts',
       'Local_Other Sales and Service Rev', 'Local_Student Fees NonSpecified',
       'Local_Interest Earnings', 'Local_Miscellaneous Other Local Rev',
       'Local_Special Processing', 'Local_Rents and Royalties',
       'Local_Sale of Property', 'Local_Fines and Forfeits',
       'Local_Private Contributions', 'State_General Formula Assistance',
       'State_Special Education Programs', 'State_Transportation Programs',
       'State_Staff Improvement Programs',
       'State_Compensat and Basic Skills Prog',
       'State_Vocational Education Programs',
       'State_Capital Outlay and Debt ServProg',
       'State_Bilingual Education Programs',
       'State_Gifted and Talented Programs', 'State_School Lunch Programs',
       'State_All Other Rev', 'State_Payment for LEA Empl_Benefits',
       'State_Other State Payments', 'State_Non-Specified',
       'Federal_Federal Title I Revenue', 'Federal_Children with Disabilities',
       'Federal_Child Nutrition Act', 'Federal_ Eisenhower Math and Science',
       'Federal_Drug_Free_Schools', 'Federal_Vocational Education',
       'Federal_ All Other Fed_Aid Through State', 'Federal_Nonspecified',
       'Federal_Impact Aid', 'Federal_Bilingual Education',
       'Federal_Native American', 'Federal_All Other Federal Aid',
       'Total Local Revenue', 'Total State Revenue', 'Total Federal Revenue',
       'Total Revenue'],
      dtype='object')

In [24]:
total_revenue = all_revenue_df.drop(all_revenue_df.columns[0:-4], axis = 1)
total_revenue.head(10)

,Total Local Revenue,Total State Revenue,Total Federal Revenue,Total Revenue
0,171312000.0,39046000.0,15893000.0,226251000.0
1,27481000.0,8624000.0,1605000.0,37710000.0
2,3714000.0,473000.0,223000.0,4410000.0
3,25820000.0,2913000.0,1250000.0,29983000.0
4,96654000.0,12463000.0,10906000.0,120023000.0
5,0.0,0.0,0.0,0.0
6,40170000.0,9711000.0,5914000.0,55795000.0
7,76372000.0,14285000.0,5985000.0,96642000.0
8,45387000.0,6761000.0,6063000.0,58211000.0
9,759000.0,303000.0,61000.0,1123000.0

In [25]:
district = df.iloc[:, 0:2]
district

,Agency Name,State Name [District] Latest available year
0,ABC UNIFIED,California
1,ACALANES UNION HIGH,California
2,ACKERMAN CHARTER,California
3,ACTON-AGUA DULCE UNIFIED,California
4,ADELANTO ELEMENTARY,California
5,ALAMEDA CNTY. STUDENT EXCHANGE PROG.,California
6,ALAMEDA COUNTY OFFICE OF EDUCATION,California
7,ALAMEDA UNIFIED,California
8,ALBANY CITY UNIFIED,California
9,ALEXANDER VALLEY UNION ELEMENTARY,California
10,ALHAMBRA UNIFIED,California
11,ALISAL UNION,California
12,ALLENSWORTH ELEMENTARY,California
13,ALPAUGH UNIFIED,California
14,ALPINE COUNTY OFFICE OF EDUCATION,California
15,ALPINE COUNTY UNIFIED,California
16,ALPINE UNION ELEMENTARY,California
17,ALTA LOMA ELEMENTARY,California
18,ALTA VISTA ELEMENTARY,California
19,ALTA-DUTCH FLAT UNION ELEMENTARY,California
20,ALUM ROCK UNION ELEMENTARY,California
21,ALVIEW-DAIRYLAND UNION ELEMENTARY,California
22,ALVINA ELEMENTARY,California
23,ALVORD UNIFIED,California
24,AMADOR COUNTY OFFICE OF EDUCATION,California
25,AMADOR COUNTY ROP,California
26,AMADOR COUNTY UNIFIED,California
27,ANAHEIM ELEMENTARY,California
28,ANAHEIM UNION HIGH,California
29,ANDERSON UNION HIGH,California
...,...,...
1138,WILLOW GROVE UNION ELEMENTARY,California
1139,WILLOWS UNIFIED,California
1140,WILMAR UNION ELEMENTARY,California
1141,WILSONA ELEMENTARY,California
1142,WINDSOR UNIFIED,California
1143,WINSHIP-ROBBINS,California
1144,WINTERS JOINT UNIFIED,California
1145,WINTON,California
1146,WISEBURN UNIFIED,CALIFORNIA
1147,WOODLAKE UNIFIED,California
1148,WOODLAND JOINT UNIFIED,California
1149,WOODSIDE ELEMENTARY,California
1150,WOODVILLE UNION ELEMENTARY,California
1151,WRIGHT ELEMENTARY,California
1152,YOLO COUNTY OFFICE OF EDUCATION,California
1153,YOLO COUNTY ROP,California
1154,YOSEMITE ROP,California
1155,YOSEMITE UNIFIED,California
1156,YREKA UNION ELEMENTARY,California
1157,YREKA UNION HIGH,California
1158,YUBA CITY UNIFIED,California
1159,YUBA COUNTY OFFICE OF EDUCATION,California
1160,YUCAIPA-CALIMESA JOINT UNIFIED,California
1161,NaN,NaN
1162,NaN,NaN
1163,Data Source: U.S. Department of Education Nati...,NaN
1164,NaN,NaN
1165,† indicates that the data are not applicable.,NaN
1166,– indicates that the data are missing.,NaN
1167,‡ indicates that the data do not meet NCES dat...,NaN

In [26]:
new_df = pd.merge(district, total_revenue, left_index=True, right_index=True)
new_df

,Agency Name,State Name [District] Latest available year,Total Local Revenue,Total State Revenue,Total Federal Revenue,Total Revenue
0,ABC UNIFIED,California,171312000.0,39046000.0,15893000.0,226251000.0
1,ACALANES UNION HIGH,California,27481000.0,8624000.0,1605000.0,37710000.0
2,ACKERMAN CHARTER,California,3714000.0,473000.0,223000.0,4410000.0
3,ACTON-AGUA DULCE UNIFIED,California,25820000.0,2913000.0,1250000.0,29983000.0
4,ADELANTO ELEMENTARY,California,96654000.0,12463000.0,10906000.0,120023000.0
5,ALAMEDA CNTY. STUDENT EXCHANGE PROG.,California,0.0,0.0,0.0,0.0
6,ALAMEDA COUNTY OFFICE OF EDUCATION,California,40170000.0,9711000.0,5914000.0,55795000.0
7,ALAMEDA UNIFIED,California,76372000.0,14285000.0,5985000.0,96642000.0
8,ALBANY CITY UNIFIED,California,45387000.0,6761000.0,6063000.0,58211000.0
9,ALEXANDER VALLEY UNION ELEMENTARY,California,759000.0,303000.0,61000.0,1123000.0
10,ALHAMBRA UNIFIED,California,149777000.0,69201000.0,31160000.0,250138000.0
11,ALISAL UNION,California,83568000.0,13610000.0,12363000.0,109541000.0
12,ALLENSWORTH ELEMENTARY,California,871000.0,116000.0,118000.0,1105000.0
13,ALPAUGH UNIFIED,California,3832000.0,565000.0,624000.0,5021000.0
14,ALPINE COUNTY OFFICE OF EDUCATION,California,1108000.0,172000.0,167000.0,1447000.0
15,ALPINE COUNTY UNIFIED,California,888000.0,308000.0,518000.0,1714000.0
16,ALPINE UNION ELEMENTARY,California,10410000.0,2122000.0,901000.0,13433000.0
17,ALTA LOMA ELEMENTARY,California,45511000.0,6821000.0,2777000.0,55109000.0
18,ALTA VISTA ELEMENTARY,California,5325000.0,783000.0,995000.0,7103000.0
19,ALTA-DUTCH FLAT UNION ELEMENTARY,California,566000.0,133000.0,95000.0,794000.0
20,ALUM ROCK UNION ELEMENTARY,California,81282000.0,17682000.0,14255000.0,113219000.0
21,ALVIEW-DAIRYLAND UNION ELEMENTARY,California,2466000.0,487000.0,399000.0,3352000.0
22,ALVINA ELEMENTARY,California,1532000.0,136000.0,101000.0,1769000.0
23,ALVORD UNIFIED,California,169894000.0,32776000.0,19938000.0,222608000.0
24,AMADOR COUNTY OFFICE OF EDUCATION,California,10585000.0,1079000.0,1195000.0,12859000.0
25,AMADOR COUNTY ROP,California,0.0,0.0,0.0,0.0
26,AMADOR COUNTY UNIFIED,California,10336000.0,5267000.0,1912000.0,17515000.0
27,ANAHEIM ELEMENTARY,California,116382000.0,33643000.0,14690000.0,164715000.0
28,ANAHEIM UNION HIGH,California,252912000.0,58792000.0,38103000.0,349807000.0
29,ANDERSON UNION HIGH,California,13268000.0,2939000.0,1531000.0,17738000.0
...,...,...,...,...,...,...
1138,WILLOW GROVE UNION ELEMENTARY,California,41000.0,22000.0,17000.0,80000.0
1139,WILLOWS UNIFIED,California,9741000.0,1553000.0,1062000.0,12356000.0
1140,WILMAR UNION ELEMENTARY,California,690000.0,407000.0,129000.0,1226000.0
1141,WILSONA ELEMENTARY,California,12515000.0,1838000.0,1868000.0,16221000.0
1142,WINDSOR UNIFIED,California,31197000.0,6964000.0,3400000.0,41561000.0
1143,WINSHIP-ROBBINS,California,1988000.0,337000.0,164000.0,2489000.0
1144,WINTERS JOINT UNIFIED,California,12564000.0,2567000.0,1208000.0,16339000.0
1145,WINTON,California,18820000.0,3615000.0,3040000.0,25475000.0
1146,WISEBURN UNIFIED,CALIFORNIA,29619000.0,35763000.0,954000.0,66336000.0
1147,WOODLAKE UNIFIED,California,22755000.0,4715000.0,3370000.0,30840000.0
1148,WOODLAND JOINT UNIFIED,California,73105000.0,15635000.0,8440000.0,97180000.0
1149,WOODSIDE ELEMENTARY,California,13675000.0,865000.0,96000.0,14636000.0
1150,WOODVILLE UNION ELEMENTARY,California,4503000.0,690000.0,1144000.0,6337000.0
1151,WRIGHT ELEMENTARY,California,12155000.0,2300000.0,1360000.0,15815000.0
1152,YOLO COUNTY OFFICE OF EDUCATION,California,28171000.0,3974000.0,10773000.0,42918000.0
1153,YOLO COUNTY ROP,California,0.0,0.0,0.0,0.0
1154,YOSEMITE ROP,California,0.0,0.0,0.0,0.0
1155,YOSEMITE UNIFIED,California,12881000.0,3060000.0,1278000.0,17219000.0
1156,YREKA UNION ELEMENTARY,California,6935000.0,1028000.0,1473000.0,9436000.0
1157,YREKA UNION HIGH,California,4993000.0,1205000.0,638000.0,6836000.0
1158,YUBA CITY UNIFIED,California,102837000.0,22711000.0,11731000.0,137279000.0
1159,YUBA COUNTY OFFICE OF EDUCATION,California,20818000.0,3279000.0,5200000.0,29297000.0
1160,YUCAIPA-CALIMESA JOINT UNIFIED,California,73160000.0,13339000.0,7105000.0,93604000.0
1161,NaN,NaN,0.0,0.0,0.0,0.0
1162,NaN,NaN,0.0,0.0,0.0,0.0
1163,Data Source: U.S. Department of Education Nati...,NaN,0.0,0.0,0.0,0.0
1164,NaN,NaN,0.0,0.0,0.0,0.0
1165,† indicates that the data are not applicable.,NaN,0.0,0.0,0.0,0.0
1166,– indicates that the data are missing.,NaN,0.0,0.0,0.0,0.0
1167,‡ indicates that the data do not meet NCES dat...,NaN,0.0,0.0,0.0,0.0

In [27]:
new_df.to_csv('total_revenue_per_district.csv', index=True)